### ISSUE TITLE
difficult to contact MYK Freifunk community

### ISSUE THREAD

**Issue by nudelkiste** [FreifunkMYK/website#1]
Hi, 

auf eurer Website, gibt es öfter Links zum Kontaktaufnehmen. Die führen aber leider ins digitale Nirvana, z.B.:
https://freifunk-myk.de/kontakt
https://freifunk-myk.de/impressum/
beide enden mit:
404 Not Found
nginx

Wie kann man also zu euch Kontakt aufnehmen um z.B. zu bitten grafana wieder zu reparieren?
z.B.: https://map.freifunk-myk.de/#!/de/map/e894f6335d98
![image](https://user-images.githubusercontent.com/47867405/112386588-6ede4700-8cf1-11eb-9f4f-fe31a983358c.png)

Wenn man drauf klickt, dann gelangt man hier hin:
https://statistics.freifunk-myk.de/d/000000001/ffmyk-knoten?var-node=e894f6335d98
![image](https://user-images.githubusercontent.com/47867405/112386732-9c2af500-8cf1-11eb-878c-eb0783856e62.png)
So richtig hilft das auch nicht weiter "no data" ;-)

Grüße
Sebastian Fontaine

**Comment by niyawe** [comment]
Hi,

die kaputten Links habe ich behoben. Das Grafana-Problem ist bekannt. Da müsste der @adlerweb mal nach schauen.

**Comment by kreativmonkey** [comment]
Da das problem behoben ist wird der Issue geschlossen, grafana gehört nicht zur Webseite direkt sondern ist an einer anderen Stelle organisiert.
